#!/usr/bin/env ruby
Dir.chdir(ENV.fetch("ROOT", "/home/app/decidim")) do 
    pid_file = ENV.fetch("PIDFILE", "tmp/server.pid")
    File.delete(pid_file) if File.exists?(pid_file)
    puts "    ✅ Puma pid is removed"
end