#!/usr/bin/env ruby
require "erb"

puts "Setup templates"
root_dir = ENV.fetch("ROOT", "/home/decidim/app")
Dir.chdir(root_dir) do 
	template_directory = "/usr/local/share/decidim/templates"
	template_motd = ERB.new(File.read(File.join(template_directory, "motd.txt.erb")))
	  
	File.write("/etc/motd", template_motd.result_with_hash(
		decidim_version: ENV.fetch("DECIDIM_VERSION", "?"),
		node_version: ENV.fetch("NODE_MAJOR_VERSION", "?"),
		root: root_dir,
		rails_env: ENV.fetch("RAILS_ENV"),
		ruby_version: ENV.fetch("RUBY_VERSION")
	))
	puts "/docker-entrypoint.d/45_template:"
	puts "    ✅ /etc/motd updated"
end