#! /bin/sh
set -e
cd $ROOT
bundle exec rails c <<EOF
  if ENV["DECIDIM_SYSTEM_EMAIL"].present? && ENV["DECIDIM_SYSTEM_PASSWORD"].present?
    admin = Decidim::System::Admin.where(email: ENV["DECIDIM_SYSTEM_EMAIL"]).first_or_initialize(
      email: ENV["DECIDIM_SYSTEM_EMAIL"],
      password: ENV["DECIDIM_SYSTEM_PASSWORD"],
      password_confirmation: ENV["DECIDIM_SYSTEM_PASSWORD"]
    )
    admin.password_confirmation = admin.password = ENV["DECIDIM_SYSTEM_PASSWORD"]
    admin.save
	  puts "/docker-entrypoint.d/50_upsert-sysadmin:"
    puts "    ✅ /system DECIDIM_SYSTEM_EMAIL account updated."
  end
EOF
