#! /bin/sh
set -e
cd $ROOT
bundle exec rails c <<EOF
  if ENV["DECIDIM_SYSTEM_EMAIL"].present? && ENV["DECIDIM_SYSTEM_PASSWORD"].present?
    Decidim::System::Admin.first_or_create(
      email: ENV["DECIDIM_SYSTEM_EMAIL"], 
      password: ENV["DECIDIM_SYSTEM_PASSWORD"],
      password_confirmation: ENV["DECIDIM_SYSTEM_PASSWORD"]
    )
    puts "    ✅ /system account created from DECIDIM_SYSTEM_EMAIL"
  end
EOF
