=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHubClient::RepositoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RepositoriesApi' do
  before do
    # run before each test
    @api_instance = DockerHubClient::RepositoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepositoriesApi' do
    it 'should create an instance of RepositoriesApi' do
      expect(@api_instance).to be_instance_of(DockerHubClient::RepositoriesApi)
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_get
  # List repository tags
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number to get. Defaults to 1.
  # @option opts [Integer] :page_size Number of items to get per page. Defaults to 10. Max of 100.
  # @return [PaginatedTags]
  describe 'v2_namespaces_namespace_repositories_repository_tags_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_head
  # Check repository tags
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_namespaces_namespace_repositories_repository_tags_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_tag_get
  # Read repository tag
  # @param namespace 
  # @param repository 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'v2_namespaces_namespace_repositories_repository_tags_tag_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_tag_head
  # Check repository tag
  # @param namespace 
  # @param repository 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_namespaces_namespace_repositories_repository_tags_tag_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
