default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") { "postgresql" } %>
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_MAX_POOL_SIZE") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
  <% if ENV["DATABASE_URL"].to_s != "" %>
  url: <%= ENV["DATABASE_URL"].inspect %>
  <% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
