#!/usr/bin/env ruby
require 'open3'

Dir.chdir("/home/decidim") do 
  exit 0 unless ENV["DECIDIM_SYSTEM_EMAIL"] && ENV["DECIDIM_SYSTEM_PASSWORD"]
  puts "#{__FILE__}:"
  console_script = <<~RB
      admin = Decidim::System::Admin.find_or_initialize_by(
        email: ENV["DECIDIM_SYSTEM_EMAIL"]
      )
      admin.password_confirmation = admin.password = ENV["DECIDIM_SYSTEM_PASSWORD"]
      admin.save!
RB
  Open3.popen3("bundle exec rails c") do |stdin, stdout, stderr, wait_thr|
    stdin.puts console_script
    stdin.close
  end
  puts "    ✅ /system DECIDIM_SYSTEM_EMAIL account updated."
  exit 0
end
