#!/usr/bin/env ruby
require "erb"
require 'bundler'

def find_version(gem_name)
	match = Bundler.load.specs.find { |s| s.name == gem_name }
	return "?" unless match
	match.version
end

system("bundle check || bundle install", exception: true)
Dir.chdir("/home/decidim") do 
	puts "#{__FILE__}:"
	motd_content = <<~MOTD
▄ ▄▖▄▖▄▖▄ ▄▖▖  ▖
▌▌▙▖▌ ▐ ▌▌▐ ▛▖▞▌
▙▘▙▖▙▖▟▖▙▘▟▖▌▝ ▌
v<%= decidim_version %> 

rails env:\t<%= rails_env %>
home:\t\t/home/decidim
build:\t\t#<%= os_version %>, <%= build_date %>

ruby#<%= ruby_version %>,bundler#<%= bundler_version %>,node#<%= node_version %>
MOTD
	template_motd = ERB.new(motd_content)
	  
	File.write("/etc/motd", template_motd.result_with_hash(
		decidim_version: find_version("decidim-core"),
		node_version: %x(node -v).strip.match(/v(\d+\.\d+\.\d+)/)[1],
		rails_env: ENV.fetch("RAILS_ENV"),
		ruby_version: ENV.fetch("RUBY_VERSION"),
		bundler_version: ENV.fetch("BUNDLER_VERSION"),
		whoami: %x(whoami).strip,
		build_date: Time.now.strftime("%Y-%m-%d %H:%M:%S"),
		os_version: File.read("/etc/os-release").match(/VERSION_ID="([^"]+)"/)[1]
	))
	puts "    ✅ /etc/motd updated"
end

exit 0