name: Build Decidim Docker images (Redhat)

env:
  VERBOSE: 1
  DOCKER_HUB_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

on:
  workflow_dispatch:
  schedule:
    # Every day at 19:00, we udpdate images
    - cron:  '0 19 * * *'

jobs:
  redhat-decidim-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Rubies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          setup-rbenv: true
      - name: Build image
        run: |
          bundle install
          bundle exec rake docker:build:redhat[dev]
      - name: Push image
        run: |
          bundle exec rake docker:push:redhat[dev]
      - name: Clean Docker clone directory
        run: |
          bundle exec rake docker:clean
          
  redhat-decidim-last:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Rubies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          setup-rbenv: true
      - name: Build image
        run: |
          bundle install
          bundle exec rake docker:build:redhat[last]
      - name: Push image
        run: |
          bundle exec rake docker:push:redhat[last]
      - name: Clean Docker clone directory
        run: |
          bundle exec rake docker:clean

  redhat-decidim-prev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Rubies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          setup-rbenv: true
      - name: Build image
        run: |
          bundle install
          bundle exec rake docker:build:redhat[prev]
      - name: Push image
        run: |
          bundle exec rake docker:push:redhat[prev]
      - name: Clean Docker clone directory
        run: |
          bundle exec rake docker:clean

  redhat-decidim-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Rubies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          setup-rbenv: true
      - name: Build image
        run: |
          bundle install
          bundle exec rake docker:build:redhat[legacy]
      - name: Push image
        run: |
          bundle exec rake docker:push:redhat[legacy]
      - name: Clean Docker clone directory
        run: |
          bundle exec rake docker:clean